
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RO = 10;
  public static final int INT = 2;
  public static final int CM = 9;
  public static final int COL_DASH = 7;
  public static final int EOF = 0;
  public static final int RC = 11;
  public static final int DOT = 8;
  public static final int QM_DASH = 6;
  public static final int REAL = 3;
  public static final int error = 1;
  public static final int VAR_STRING = 5;
  public static final int ATOM_STRING = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "REAL",
  "ATOM_STRING",
  "VAR_STRING",
  "QM_DASH",
  "COL_DASH",
  "DOT",
  "CM",
  "RO",
  "RC"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[10]=new String("RO");
		TT[2]=new String("INT");
		TT[9]=new String("CM");
		TT[7]=new String("COL_DASH");
		TT[0]=new String("EOF");
		TT[11]=new String("RC");
		TT[8]=new String("DOT");
		TT[6]=new String("QM_DASH");
		TT[3]=new String("REAL");
		TT[1]=new String("error");
		TT[5]=new String("VAR_STRING");
		TT[4]=new String("ATOM_STRING");
	}
public String getTT(int i){return TT[i];}
}

